[package]
name = "rank-up"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[dependencies]
itertools = "0.15.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.10.2"
ntest = "0.9"

[[bench]]
name = "selection_sort_benchmark"
harness = false

[profile.dev]
debug = 0
incremental = false

[profile.test]
debug = 0
incremental = false
